[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

authors = [
  { name="DrZuse", email="none"},
]

[project]
name = "chatgpt_automation"
description = "A Headless Chrome interface to communicate with ChatGPT"
readme = "README.md"
requires-python = ">=3.8"
version = "0.1.5"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
   'selenium>=4.7.2',
   'undetected-chromedriver>=3.4.6'
]

[project.urls]
Source = "https://github.com/DrZuse/ChatGPT_Automation"